#*****************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# emp_generic_mgt.tcl: Tcl script for re-creating project 'emp_generic_mgt_v1_0_project'
#
# Generated by Vivado on Wed Nov 20 09:45:21 CET 2024
# IP Build 4028589 on Sat Oct 14 00:45:43 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (emp_generic_mgt.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_12/mgt_channel_12.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_11/mgt_channel_11.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_10/mgt_channel_10.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_9/mgt_channel_9.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_8/mgt_channel_8.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_7/mgt_channel_7.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_6/mgt_channel_6.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_5/mgt_channel_5.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_4/mgt_channel_4.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_3/mgt_channel_3.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_2/mgt_channel_2.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_1/mgt_channel_1.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_0/mgt_channel_0.xci"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/emp_transceiver_channel_gthe4_common_wrapper.v"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/gtwizard_ultrascale_v1_7_gthe4_common.v"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/all_mgt.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/fifo_fill_level_acc.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/xlx_ku_mgt_ip_reset_synchronizer.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_0.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_1.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_10.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_11.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_12.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_2.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_3.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_4.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_5.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_6.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_7.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_8.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/mgt_channel_inst_9.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/tx_phase_aligner.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/tx_phase_aligner_fsm.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/tx_pi_ctrl.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/src/transceivers.vhd"
#    "/home/decker/Documents/vivadoProj/master/emp-firmware/emp_generic_mgt/component.xml"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_12/mgt_channel_12.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_11/mgt_channel_11.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_10/mgt_channel_10.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_9/mgt_channel_9.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_8/mgt_channel_8.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_7/mgt_channel_7.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_6/mgt_channel_6.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_5/mgt_channel_5.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_4/mgt_channel_4.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_3/mgt_channel_3.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_2/mgt_channel_2.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_1/mgt_channel_1.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_0/mgt_channel_0.xci"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/emp_transceiver_channel_gthe4_common_wrapper.v"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/gtwizard_ultrascale_v1_7_gthe4_common.v"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/all_mgt.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/fifo_fill_level_acc.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/xlx_ku_mgt_ip_reset_synchronizer.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_0.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_1.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_10.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_11.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_12.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_2.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_3.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_4.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_5.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_6.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_7.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_8.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_9.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/tx_phase_aligner.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/tx_phase_aligner_fsm.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/tx_pi_ctrl.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/src/transceivers.vhd"]"\
 "[file normalize "$origin_dir/emp_generic_mgt/component.xml"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "emp_generic_mgt_v1_0_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "emp_generic_mgt.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/emp-firmware-2023.2/emp-firmware-2023.2.tmp/emp_generic_mgt_v1_0_project"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
file rename -force "${_xil_proj_name_}/${_xil_proj_name_}.srcs" "${_xil_proj_name_}/folder_aux"
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xczu4eg-fbvb900-1-e
file delete -force "${_xil_proj_name_}/${_xil_proj_name_}.srcs"
file rename -force "${_xil_proj_name_}/folder_aux" "${_xil_proj_name_}/${_xil_proj_name_}.srcs"
# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -id {IP_Flow 19-2403}  -suppress  -ruleid {1}  -source 16
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:sp701:part0:1.0 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/sp701/1.0/board.xml as part xc7s100fgga676-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {10}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:sp701:part0:1.1 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/sp701/1.1/board.xml as part xc7s100fgga676-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {11}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vc707:part0:1.4 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vc707/1.4/board.xml as part xc7vx485tffg1761-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {12}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vc709:part0:1.8 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vc709/1.8/board.xml as part xc7vx690tffg1761-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {13}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190:part0:2.2 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190/production/2.2/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {14}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190:part0:3.0 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190/production/3.0/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {15}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190:part0:3.1 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190/production/3.1/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {16}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190:part0:3.2 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190/production/3.2/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {17}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190_newl:part0:1.0 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190_newl/production/1.0/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {18}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:vck190_newl:part0:1.1 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/vck190_newl/production/1.1/board.xml as part xcvc1902-vsva2197-2mp-e-s specified in board_part file is either invalid or not available}}  -suppress  -ruleid {19}  -source 8
set_msg_config  -id {Synth 8-7080}  -suppress  -ruleid {2}  -source 16
set_msg_config  -id {IP_Flow 19-4295}  -string {{CRITICAL WARNING: [IP_Flow 19-4295] Component Definition 'user.org:user:transceivers_firefly:1.0 (transceivers_firefly_v1_0)': A core property canUpgradeFrom 'user.org:user:transceivers_firefly:1.0' with a version that is greater or equal to the current version '1.0' of the IP.}}  -suppress  -ruleid {20}  -source 8
set_msg_config  -id {Designutils 20-1280}  -new_severity {WARNING}  -ruleid {22}  -source 2
set_msg_config  -id {Synth 8-7129}  -suppress  -ruleid {25}  -source 16
set_msg_config  -id {Board 49-26}  -suppress  -ruleid {26}  -source 16
set_msg_config  -id {17-179}  -suppress  -ruleid {4}  -source 2
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:ac701:part0:1.4 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/ac701/1.4/board.xml as part xc7a200tfbg676-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {5}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:kc705:part0:1.6 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/kc705/1.6/board.xml as part xc7k325tffg900-2 specified in board_part file is either invalid or not available}}  -suppress  -ruleid {6}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:kcu105:part0:1.6 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu105/1.6/board.xml as part xcku040-ffva1156-2-e specified in board_part file is either invalid or not available}}  -suppress  -ruleid {7}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:kcu105:part0:1.7 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu105/1.7/board.xml as part xcku040-ffva1156-2-e specified in board_part file is either invalid or not available}}  -suppress  -ruleid {8}  -source 8
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:kcu1500:part0:1.2 available at /home/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/kcu1500/1.2/board.xml as part xcku115-flvb2104-2-e specified in board_part file is either invalid or not available}}  -suppress  -ruleid {9}  -source 8


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "feature_set" -value "FeatureSet_Classic" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xczu4eg-fbvb900-1-e" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_12/mgt_channel_12.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_11/mgt_channel_11.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_10/mgt_channel_10.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_9/mgt_channel_9.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_8/mgt_channel_8.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_7/mgt_channel_7.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_6/mgt_channel_6.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_5/mgt_channel_5.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_4/mgt_channel_4.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_3/mgt_channel_3.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_2/mgt_channel_2.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_1/mgt_channel_1.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_0/mgt_channel_0.xci"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/emp_transceiver_channel_gthe4_common_wrapper.v"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/gtwizard_ultrascale_v1_7_gthe4_common.v"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/all_mgt.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/fifo_fill_level_acc.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/xlx_ku_mgt_ip_reset_synchronizer.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_0.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_1.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_10.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_11.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_12.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_2.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_3.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_4.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_5.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_6.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_7.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_8.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/mgt_channel_inst_9.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/tx_phase_aligner.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/tx_phase_aligner_fsm.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/tx_pi_ctrl.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/src/transceivers.vhd"] \
 [file normalize "${origin_dir}/emp_generic_mgt/component.xml"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/emp_generic_mgt/src/mgt_channel_12/mgt_channel_12.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_11/mgt_channel_11.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_10/mgt_channel_10.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_9/mgt_channel_9.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_8/mgt_channel_8.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_7/mgt_channel_7.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_6/mgt_channel_6.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_5/mgt_channel_5.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_4/mgt_channel_4.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_3/mgt_channel_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_2/mgt_channel_2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_1/mgt_channel_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_0/mgt_channel_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/emp_transceiver_channel_gthe4_common_wrapper.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/gtwizard_ultrascale_v1_7_gthe4_common.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/all_mgt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/fifo_fill_level_acc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/xlx_ku_mgt_ip_reset_synchronizer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_0.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_1.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_10.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_11.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_12.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_4.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_5.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_6.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_7.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_8.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/mgt_channel_inst_9.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/tx_phase_aligner.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/tx_phase_aligner_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/tx_pi_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/src/transceivers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/emp_generic_mgt/component.xml"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "IP-XACT" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "emp_generic_mgt" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_file" -value "emp_generic_mgt/src/transceivers.vhd" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xczu4eg-fbvb900-1-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "emp_generic_mgt" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xczu4eg-fbvb900-1-e -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xczu4eg-fbvb900-1-e" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xczu4eg-fbvb900-1-e -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xczu4eg-fbvb900-1-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
